import torch

def cublas_gemm_nt(a: torch.Tensor, b: torch.Tensor, c: torch.Tensor) -> None: ...
def cublas_gemmex_nt(a: torch.Tensor, b: torch.Tensor, c: torch.Tensor) -> None: ...

def cutlass_gemm_nt_naive(
    a: torch.Tensor, b: torch.Tensor, c: torch.Tensor
) -> None: ...
def cutlass_gemm_nt_manual_tune(
    a: torch.Tensor, b: torch.Tensor, c: torch.Tensor
) -> None: ...